### PR TITLE
TypeScript definitions

### PR DESCRIPTION
**Pull request by suda**
This PR adds automatic generation of TypeScript type definitions for both protobuf and main JS files.

It also renames `_pbjsobjects` to `definitions` to allow following syntax:

```ts
import DeviceOSProtobuf from '@particle/device-os-protobuf';
const decoded = DeviceOSProtobuf.decode(DeviceOSProtobuf.definitions.wifi.ScanNetworksReply, data);
```

Note: I had to move the `enum` declaration in `nanopb.proto` file due to a [`protobufjs` bug](https://github.com/protobufjs/protobuf.js/issues/1414)

### CODE REVIEW

**Review by joegoggins — APPROVED** [review]
Looks good.

I pushed a commit updating the release process to reflect reality; 719be4a. After addressing whatever feedback others have on this PR, feel free to cut a patch release after merging.

Also, if you could share a link to the Shortcut story that will utilize these typescript definitions, that'd be great, I'll like to follow along with that work.

**Review by monkbroc — APPROVED** [review]
I'm not going to review the 11k line definition file. I assume that any issues that crop up in the definitions, we'll fix in another PR :)

**Comment by sergeuz** [comment]
Why do we store generated JavaScript and TypeScript files in the repo?

**Comment by sergeuz** [comment]
Once the [device-control](https://github.com/particle-iot-inc/device-control/tree/monorepo) monorepo is in a good shape, I'll move all the JS/TS definitions from this repo there and hard reset this repo to the commit when it only had .proto definitions. Any objections to that?

**Comment by suda** [comment]
@joegoggins thanks! Here's the [shortcut story](https://app.shortcut.com/particle/story/94352/implement-the-protobuf-communication-protocol?cf_workflow=500127125&ct_workflow=all) I'm tracking my work in

@sergeuz true, we don't need to store the generated `.d.ts` files in this repo, I'll add a `.gitignore` :)

As for resetting this repo, you're still intending on publishing it as a npm package so we don't do `git submodule` in `device-control` right?

**Comment by sergeuz** [comment]
> As for resetting this repo, you're still intending on publishing it as a npm package so we don't do git submodule in device-control right?

@suda We'll be using this repo as a submodule in `@particle/device-control-protobuf`, but consumers of that npm module won't need to build any protobuf definitions. So, essentially, `@particle/device-control-protobuf` will be a drop-in replacement for JS/TS projects that rely on `@particle/device-os-protobuf` now.

**Pull request merged**
